### PR TITLE
Update github-changes to 0.0.16

### PR DESCRIPTION
**Pull request by sethkinast**
Also fixes some small README issues

### CODE REVIEW

**Comment by streetlight** [comment]
@sethkinast Ah thanks for the catch!

**Comment by sethkinast** [comment]
Cool, thanks. Once you push a new version we'll start depping this plugin.

**Comment by streetlight** [comment]
@sethkinast Sounds awesome. Just pushed new version. Hope this helps (and glad to hear you find it helpful)!

**Comment by sethkinast** [comment]
Thanks!

**Pull request merged**
